In [21]:
from pprint import pprint
import numpy as np
from litedl.layers import Affine, Sigmoid, ReLU, MSE

x = np.random.randn(10, 3)
t = np.random.randn(10, 1)

affine1 = Affine(input_size=3, output_size=5)
sigmoid = Sigmoid()
affine2 = Affine(input_size=5, output_size=1)
relu = ReLU()
mse = MSE()

output = affine1.forward(x)
output = sigmoid.forward(output)
output = affine2.forward(output)
output = relu.forward(output)
output = mse.forward(output, t)
print(output)

dout = mse.backward()
dout = relu.backward(dout)
dout = affine2.backward(dout)
dout = sigmoid.backward(dout)
dout = affine1.backward(dout)

print(dout)
print(affine1.grads)
print(affine2.grads)

2.8168606130371012
[[-0.04412396 -0.29706904 -0.20772326]
 [ 0.          0.          0.        ]
 [-0.07172898 -0.23625128 -0.17499648]
 [-0.08015581 -0.443754   -0.30633634]
 [-0.00276904 -0.03955083 -0.0307054 ]
 [ 0.01577414  0.01777311  0.02119709]
 [-0.01907169 -0.20464114 -0.14785623]
 [-0.06743914 -0.34834585 -0.24023952]
 [-0.00299875 -0.12315346 -0.08655603]
 [ 0.04208486 -0.41147596 -0.23102991]]
{'W': array([[-0.58721674,  0.44113395,  0.12377821, -0.8917794 , -0.10037254],
       [-0.91193063,  0.53390763,  0.15781582, -0.90367781, -0.09644161],
       [-0.153369  ,  0.38381523,  0.02224257, -0.51037486, -0.12451232]]), 'b': array([ 0.88132879, -0.56072706, -0.13586545,  0.98568748,  0.11111356])}
{'W': array([[2.12853287],
       [0.78980536],
       [1.44967779],
       [1.87766672],
       [1.00069822]]), 'b': array([2.71771723])}
